#include <AP_Common/AP_Common.h>
#include <AP_Param/AP_Param.h>

#ifndef _OREIENTATION_H
#define _OREIENTATION_H

int get_orientation_roll(uint8_t dir) {
    switch(dir) {
        case MAV_SENSOR_ROTATION_NONE:
            return 0;
        case MAV_SENSOR_ROTATION_YAW_45:
            return 0;
        case MAV_SENSOR_ROTATION_YAW_90:
            return 0;
        case MAV_SENSOR_ROTATION_YAW_135:
            return 0;
        case MAV_SENSOR_ROTATION_YAW_180:
            return 0;
        case MAV_SENSOR_ROTATION_YAW_225:
            return 0;
        case MAV_SENSOR_ROTATION_YAW_270:
            return 0;
        case MAV_SENSOR_ROTATION_YAW_315:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_180:
            return 180;
        case MAV_SENSOR_ROTATION_ROLL_180_YAW_45:
            return 180;
        case MAV_SENSOR_ROTATION_ROLL_180_YAW_90:
            return 180;
        case MAV_SENSOR_ROTATION_ROLL_180_YAW_135:
            return 180;
        case MAV_SENSOR_ROTATION_PITCH_180:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_180_YAW_225:
            return 180;
        case MAV_SENSOR_ROTATION_ROLL_180_YAW_270:
            return 180;
        case MAV_SENSOR_ROTATION_ROLL_180_YAW_315:
            return 180;
        case MAV_SENSOR_ROTATION_ROLL_90:
            return 90;
        case MAV_SENSOR_ROTATION_ROLL_90_YAW_45:
            return 90;
        case MAV_SENSOR_ROTATION_ROLL_90_YAW_90:
            return 90;
        case MAV_SENSOR_ROTATION_ROLL_90_YAW_135:
            return 90;
        case MAV_SENSOR_ROTATION_ROLL_270:
            return 270;
        case MAV_SENSOR_ROTATION_ROLL_270_YAW_45:
            return 270;
        case MAV_SENSOR_ROTATION_ROLL_270_YAW_90:
            return 270;
        case MAV_SENSOR_ROTATION_ROLL_270_YAW_135:
            return 270;
        case MAV_SENSOR_ROTATION_PITCH_90:
            return 0;
        case MAV_SENSOR_ROTATION_PITCH_270:
            return 0;
        case MAV_SENSOR_ROTATION_PITCH_180_YAW_90:
            return 0;
        case MAV_SENSOR_ROTATION_PITCH_180_YAW_270:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_90_PITCH_90:
            return 90;
        case MAV_SENSOR_ROTATION_ROLL_180_PITCH_90:
            return 180;
        case MAV_SENSOR_ROTATION_ROLL_270_PITCH_90:
            return 270;
        case MAV_SENSOR_ROTATION_ROLL_90_PITCH_180:
            return 90;
        case MAV_SENSOR_ROTATION_ROLL_270_PITCH_180:
            return 270;
        case MAV_SENSOR_ROTATION_ROLL_90_PITCH_270:
            return 90;
        case MAV_SENSOR_ROTATION_ROLL_180_PITCH_270:
            return 180;
        case MAV_SENSOR_ROTATION_ROLL_270_PITCH_270:
            return 270;
        case MAV_SENSOR_ROTATION_ROLL_90_PITCH_180_YAW_90:
            return 90;
        case MAV_SENSOR_ROTATION_ROLL_90_YAW_270:
            return 90;
        case MAV_SENSOR_ROTATION_ROLL_315_PITCH_315_YAW_315:
            return 315;
        default:
            return -1;
    }
}

int get_orientation_pitch(uint8_t dir) {
    switch(dir) {
        case MAV_SENSOR_ROTATION_NONE:
            return 0;
        case MAV_SENSOR_ROTATION_YAW_45:
            return 0;
        case MAV_SENSOR_ROTATION_YAW_90:
            return 0;
        case MAV_SENSOR_ROTATION_YAW_135:
            return 0;
        case MAV_SENSOR_ROTATION_YAW_180:
            return 0;
        case MAV_SENSOR_ROTATION_YAW_225:
            return 0;
        case MAV_SENSOR_ROTATION_YAW_270:
            return 0;
        case MAV_SENSOR_ROTATION_YAW_315:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_180:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_180_YAW_45:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_180_YAW_90:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_180_YAW_135:
            return 0;
        case MAV_SENSOR_ROTATION_PITCH_180:
            return 180;
        case MAV_SENSOR_ROTATION_ROLL_180_YAW_225:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_180_YAW_270:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_180_YAW_315:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_90:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_90_YAW_45:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_90_YAW_90:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_90_YAW_135:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_270:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_270_YAW_45:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_270_YAW_90:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_270_YAW_135:
            return 0;
        case MAV_SENSOR_ROTATION_PITCH_90:
            return 90;
        case MAV_SENSOR_ROTATION_PITCH_270:
            return 270;
        case MAV_SENSOR_ROTATION_PITCH_180_YAW_90:
            return 180;
        case MAV_SENSOR_ROTATION_PITCH_180_YAW_270:
            return 180;
        case MAV_SENSOR_ROTATION_ROLL_90_PITCH_90:
            return 90;
        case MAV_SENSOR_ROTATION_ROLL_180_PITCH_90:
            return 90;
        case MAV_SENSOR_ROTATION_ROLL_270_PITCH_90:
            return 90;
        case MAV_SENSOR_ROTATION_ROLL_90_PITCH_180:
            return 180;
        case MAV_SENSOR_ROTATION_ROLL_270_PITCH_180:
            return 180;
        case MAV_SENSOR_ROTATION_ROLL_90_PITCH_270:
            return 270;
        case MAV_SENSOR_ROTATION_ROLL_180_PITCH_270:
            return 270;
        case MAV_SENSOR_ROTATION_ROLL_270_PITCH_270:
            return 270;
        case MAV_SENSOR_ROTATION_ROLL_90_PITCH_180_YAW_90:
            return 180;
        case MAV_SENSOR_ROTATION_ROLL_90_YAW_270:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_315_PITCH_315_YAW_315:
            return 315;
        default:
            return -1;
    }
}

int get_orientation_yaw(uint8_t dir) {
    switch(dir) {
        case MAV_SENSOR_ROTATION_NONE:
            return 0;
        case MAV_SENSOR_ROTATION_YAW_45:
            return 45;
        case MAV_SENSOR_ROTATION_YAW_90:
            return 90;
        case MAV_SENSOR_ROTATION_YAW_135:
            return 135;
        case MAV_SENSOR_ROTATION_YAW_180:
            return 180;
        case MAV_SENSOR_ROTATION_YAW_225:
            return 225;
        case MAV_SENSOR_ROTATION_YAW_270:
            return 270;
        case MAV_SENSOR_ROTATION_YAW_315:
            return 315;
        case MAV_SENSOR_ROTATION_ROLL_180:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_180_YAW_45:
            return 45;
        case MAV_SENSOR_ROTATION_ROLL_180_YAW_90:
            return 90;
        case MAV_SENSOR_ROTATION_ROLL_180_YAW_135:
            return 135;
        case MAV_SENSOR_ROTATION_PITCH_180:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_180_YAW_225:
            return 225;
        case MAV_SENSOR_ROTATION_ROLL_180_YAW_270:
            return 270;
        case MAV_SENSOR_ROTATION_ROLL_180_YAW_315:
            return 315;
        case MAV_SENSOR_ROTATION_ROLL_90:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_90_YAW_45:
            return 45;
        case MAV_SENSOR_ROTATION_ROLL_90_YAW_90:
            return 90;
        case MAV_SENSOR_ROTATION_ROLL_90_YAW_135:
            return 135;
        case MAV_SENSOR_ROTATION_ROLL_270:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_270_YAW_45:
            return 45;
        case MAV_SENSOR_ROTATION_ROLL_270_YAW_90:
            return 90;
        case MAV_SENSOR_ROTATION_ROLL_270_YAW_135:
            return 135;
        case MAV_SENSOR_ROTATION_PITCH_90:
            return 0;
        case MAV_SENSOR_ROTATION_PITCH_270:
            return 0;
        case MAV_SENSOR_ROTATION_PITCH_180_YAW_90:
            return 90;
        case MAV_SENSOR_ROTATION_PITCH_180_YAW_270:
            return 270;
        case MAV_SENSOR_ROTATION_ROLL_90_PITCH_90:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_180_PITCH_90:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_270_PITCH_90:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_90_PITCH_180:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_270_PITCH_180:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_90_PITCH_270:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_180_PITCH_270:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_270_PITCH_270:
            return 0;
        case MAV_SENSOR_ROTATION_ROLL_90_PITCH_180_YAW_90:
            return 90;
        case MAV_SENSOR_ROTATION_ROLL_90_YAW_270:
            return 270;
        case MAV_SENSOR_ROTATION_ROLL_315_PITCH_315_YAW_315:
            return 315;
        default:
            return -1;
    }
}

#endif // _ORIENTATION_H
